<?php

/**
 * Implements hook_preprocess_page()
 * Adds CSS for class based styling
 */
function ckeditor_youtube_preprocess_page($vars) {
  drupal_add_css(drupal_get_path('module', 'ckeditor_youtube').'/css/classes.css');
}

/**
 * Implements hook_wysiwyg_plugin().
 */
function ckeditor_youtube_wysiwyg_plugin($editor, $version) {
  $plugins = array();
  if ($editor == 'ckeditor' && version_compare($version, '4.0', '>=')) {
    $plugins['youtube'] = array(
      'url' => 'http://ckeditor.com/addon/youtube',
      'path' => drupal_get_path('module', 'ckeditor_youtube') . '/plugins/youtube',
      'buttons' => array(
        'Youtube' => t('Youtube - GSB'),
      ),
      'options' => array(
        'youtube_width' => '640',
        'youtube_height' => '480',
        'youtube_related' => TRUE,
        'youtube_older' => FALSE,
        'youtube_privacy' => FALSE,
      ),
      'load' => TRUE,
      'internal' => FALSE,
    );
  }
  return $plugins;
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */

function ckeditor_youtube_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['allowedContent'] = TRUE;
    $settings['youtube_classes'] = array(
      'ckeditor_youtube-content',
      'ckeditor_youtube-responsive'
    );
  }
}